apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: release-name-helloworld
  labels:
    helm.sh/chart: helloworld-0.0.1
    app.kubernetes.io/name: helloworld
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  endpoints:
    - interval: 30s
      port: metrics
      path:  /metrics
  jobLabel: component
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
       app.kubernetes.io/metrics: release-name-helloworld-metrics