replicaCount: 1

image:
  repository: ghcr.io/berndonline/k8s/go-helloworld
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podEnv:
  - name: RESPONSE
    value: "Hello, World - REST API!"
  - name: PORT
    value: "8080"
  - name: METRICSPORT
    value: "9100"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: 
      paths:
        - path: /helloworld(/|$)(.*)
          pathType: ImplementationSpecific

tracing:
  enabled: false
  collectorArgs: 
    - --reporter.grpc.host-port=dns:///jaeger-collector-headless.observability:14250
    - --reporter.type=grpc

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
